name: Release CI

on:
  push:
    tags:
      'v*\+uri*' # push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-yarn
    - name: Set env
      run: |
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        echo "RELEASE_NAME=${RELEASE_VERSION:1}" >> $GITHUB_ENV
    - uses: ./.github/actions/setup-pip
    - uses: ./.github/actions/setup-yarn
    - name: Build subset-utils
      run: |
        yarn workspace subset-utils run build
    - name: Build subsets
      run: |
        yarn workspace pretendard run subset
        yarn workspace pretendard-gov run subset
        yarn workspace pretendard-jp run subset
        yarn workspace pretendard-std run subset
    - name: Archive
      run: ./archive.sh
    - uses: softprops/action-gh-release@v1 # actions/create-release, actions/upload-release-asset is deprecated
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          .archive/*.zip
